apiVersion: v1
kind: ConfigMap
metadata:
  name: customer1
data:
  TEXT1: customer1_CONMPANY
  TEXT2: Welcome You
  COMPANY: Customer Company Technologies pct. Ltd.

$ kubectl create -f customer1-configmap.yaml

configmap/customer1 created